# Generated by Django 5.2.6 on 2025-10-07 19:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulcano', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Formato: +56 9 1234 5678', max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('arquitecto', 'title'), name='unique_architect_project_title'),
        ),
    ]
