# Generated by Django 5.2.6 on 2025-10-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulcano', '0003_alter_projectimage_options_projectimage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Formato: +51 999 888 666', max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
